version: "3.2"
services:
  apache:
    build: 
      context: './httpd/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./public_html/:/var/www/html/
  php:
    build: 
      context: './php/'
      args:
        - PHP_TAG=8.0-fpm-alpine3.13
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mariadb:10.5.8
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=yoursupersecretpassword
    volumes:
      - db-data:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
    ports:
      - 8080:80
    depends_on: 
    - mysql
    networks: 
    - backend
volumes:
  db-data:
networks:
  frontend:
  backend: